name: Food Ordering App Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install node modules
        run: npm i

      - name: Run tests with coverage
        run: npm run test-coverage

      - name: Codecov report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Build
        run: npm run build

      - name: Clear upload directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_API }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: rm -rf /var/www/food.ordering.app/*

      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_API }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          source: "dist/*"
          strip_components: 1
          target: "/var/www/food-ordering.app"
